# Site settings
title: Zachary Balder
name: Zachary Balder

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/zbo14
 - title: LinkedIn
   url: https://www.linkedin.com/in/zachary-balder/

#Any buzzword skills you want to include
skills:
   - Go
   - Javascript
   - Python
   - Rust

#Work experience is required
roles:
 - title: Software Engineer
   start: June 2017
   end: October 2017
   employer: Ujo Music
   description: --
 - title: Contract Developer
   start: July 2016
   end: December 2016
   employer: Raise Marketplace
   description: --

#Education is required
education:
 - level: --
   date: 2013-2016
   subject: Economics
   school: Northwestern University

#List of interesting Github repo/projects to include - optional
github:
 - zbo14/bencode-hs
 - zbo14/constellate
 - zbo14/genalg
 - zbo14/nerv

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   Open-source software engineer seeking hands-on development position.